### ISSUE TITLE
alt attribute

### ISSUE THREAD

**Issue by gdedi001** [Wishfulspoon/prj-rev-bwfs-dasmoto#3]
Don't forget to add `alt` attribute to your image tags 
https://github.com/Wishfulspoon/prj-rev-bwfs-dasmoto/blob/master/Main%20Project%201/Dasmoto's%20Arts%20%26%20Crafts/Index.html#L11

**Comment by Wishfulspoon** [comment]
It did not even occur to me! thank you!!
